name: pawsafe
description: PawSafe – Stray Dog Location Reporting System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4
  firebase_messaging: ^14.9.2

  # State management
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # Media
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # UI / Charts
  fl_chart: ^0.67.0

  # Connectivity
  connectivity_plus: ^5.0.2

  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0
  crypto: ^3.0.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/
